// Code generated by qtc from "admin.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/pages/admin.qtpl:1
package pages

//line internal/templates/pages/admin.qtpl:1
import "cms/internal/models"

//line internal/templates/pages/admin.qtpl:2
import "cms/internal/templates/layouts"

//line internal/templates/pages/admin.qtpl:3
import "strings"

//line internal/templates/pages/admin.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/pages/admin.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/pages/admin.qtpl:6
type AdminData = models.BasePageData

// {# AdminPage renders the admin placeholder page. #}

//line internal/templates/pages/admin.qtpl:10
func StreamAdminPage(qw422016 *qt422016.Writer, data *AdminData) {
//line internal/templates/pages/admin.qtpl:10
	qw422016.N().S(`
    `)
//line internal/templates/pages/admin.qtpl:12
	pageContent := func() string {
		var sb strings.Builder
		sb.WriteString(`<div class="text-center py-16">`)
		sb.WriteString(`<h1 class="text-4xl font-bold text-gray-700 mb-4">Admin Panel</h1>`)
		sb.WriteString(`<p class="text-lg text-gray-500">Coming Soon</p>`)
		sb.WriteString(`</div>`)
		return sb.String()
	}

//line internal/templates/pages/admin.qtpl:20
	qw422016.N().S(`
    `)
//line internal/templates/pages/admin.qtpl:21
	qw422016.N().S(layouts.BaseLayout(data, pageContent))
//line internal/templates/pages/admin.qtpl:21
	qw422016.N().S(`
`)
//line internal/templates/pages/admin.qtpl:22
}

//line internal/templates/pages/admin.qtpl:22
func WriteAdminPage(qq422016 qtio422016.Writer, data *AdminData) {
//line internal/templates/pages/admin.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/pages/admin.qtpl:22
	StreamAdminPage(qw422016, data)
//line internal/templates/pages/admin.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/pages/admin.qtpl:22
}

//line internal/templates/pages/admin.qtpl:22
func AdminPage(data *AdminData) string {
//line internal/templates/pages/admin.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/pages/admin.qtpl:22
	WriteAdminPage(qb422016, data)
//line internal/templates/pages/admin.qtpl:22
	qs422016 := string(qb422016.B)
//line internal/templates/pages/admin.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/pages/admin.qtpl:22
	return qs422016
//line internal/templates/pages/admin.qtpl:22
}
