// Code generated by qtc from "admin.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/pages/admin.qtpl:1
package pages

//line internal/templates/pages/admin.qtpl:1
import "cms/internal/models"

//line internal/templates/pages/admin.qtpl:2
import "cms/internal/templates/layouts"

//line internal/templates/pages/admin.qtpl:3
import "strings"

//line internal/templates/pages/admin.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/pages/admin.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/pages/admin.qtpl:6
type AdminData = models.BasePageData

//line internal/templates/pages/admin.qtpl:9
func StreamAdminPage(qw422016 *qt422016.Writer, data *AdminData) {
//line internal/templates/pages/admin.qtpl:9
	qw422016.N().S(`
    `)
//line internal/templates/pages/admin.qtpl:11
	pageContent := func() string {
		var sb strings.Builder
		sb.WriteString(`<div class="text-center py-16 sm:py-24">
                    <h1 class="text-4xl font-bold text-gray-700 dark:text-gray-200 mb-4">Admin Panel</h1>
                    <p class="text-lg text-gray-500 dark:text-gray-400">This page is under construction.</p>
                </div>`)
		return sb.String()
	}

//line internal/templates/pages/admin.qtpl:19
	qw422016.N().S(`
    `)
//line internal/templates/pages/admin.qtpl:20
	qw422016.N().S(layouts.BaseLayout(data, pageContent))
//line internal/templates/pages/admin.qtpl:20
	qw422016.N().S(`
`)
//line internal/templates/pages/admin.qtpl:21
}

//line internal/templates/pages/admin.qtpl:21
func WriteAdminPage(qq422016 qtio422016.Writer, data *AdminData) {
//line internal/templates/pages/admin.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/pages/admin.qtpl:21
	StreamAdminPage(qw422016, data)
//line internal/templates/pages/admin.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/pages/admin.qtpl:21
}

//line internal/templates/pages/admin.qtpl:21
func AdminPage(data *AdminData) string {
//line internal/templates/pages/admin.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/pages/admin.qtpl:21
	WriteAdminPage(qb422016, data)
//line internal/templates/pages/admin.qtpl:21
	qs422016 := string(qb422016.B)
//line internal/templates/pages/admin.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/pages/admin.qtpl:21
	return qs422016
//line internal/templates/pages/admin.qtpl:21
}
