// Code generated by qtc from "create.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/pages/create.qtpl:1
package pages

//line internal/templates/pages/create.qtpl:1
import "cms/internal/models"

//line internal/templates/pages/create.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/pages/create.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/pages/create.qtpl:4
// NewData struct is defined in models package
type NewData = models.NewData

// CreatePage renders the content creation form by reusing the EditPage logic.

//line internal/templates/pages/create.qtpl:9
func StreamCreatePage(qw422016 *qt422016.Writer, data *NewData) {
//line internal/templates/pages/create.qtpl:9
	qw422016.N().S(`
    `)
//line internal/templates/pages/create.qtpl:11
	// Adapt NewData to EditData for the EditPage template
	editData := &models.EditData{
		BasePageData: data.BasePageData, // Pass common data
		Item:         models.Content{},  // Empty content item for a new form
		IsNew:        true,
	}

//line internal/templates/pages/create.qtpl:17
	qw422016.N().S(`
    <!-- Render the EditPage template with adapted data -->
    `)
//line internal/templates/pages/create.qtpl:19
	qw422016.N().S(EditPage(editData))
//line internal/templates/pages/create.qtpl:19
	qw422016.N().S(`
`)
//line internal/templates/pages/create.qtpl:20
}

//line internal/templates/pages/create.qtpl:20
func WriteCreatePage(qq422016 qtio422016.Writer, data *NewData) {
//line internal/templates/pages/create.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/pages/create.qtpl:20
	StreamCreatePage(qw422016, data)
//line internal/templates/pages/create.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/pages/create.qtpl:20
}

//line internal/templates/pages/create.qtpl:20
func CreatePage(data *NewData) string {
//line internal/templates/pages/create.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/pages/create.qtpl:20
	WriteCreatePage(qb422016, data)
//line internal/templates/pages/create.qtpl:20
	qs422016 := string(qb422016.B)
//line internal/templates/pages/create.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/pages/create.qtpl:20
	return qs422016
//line internal/templates/pages/create.qtpl:20
}
