// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/pages/index.qtpl:1
package pages

//line internal/templates/pages/index.qtpl:1
import "cms/internal/models"

//line internal/templates/pages/index.qtpl:2
import "cms/internal/templates/layouts"

//line internal/templates/pages/index.qtpl:3
import "strings"

//line internal/templates/pages/index.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/pages/index.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/pages/index.qtpl:6
// IndexData struct is defined in models package
type IndexData = models.IndexData

//line internal/templates/pages/index.qtpl:10
func StreamIndexPage(qw422016 *qt422016.Writer, data *IndexData) {
//line internal/templates/pages/index.qtpl:10
	qw422016.N().S(`
    `)
//line internal/templates/pages/index.qtpl:12
	// Define the content block for the base layout
	pageContent := func() string {
		var sb strings.Builder
		sb.WriteString(`<div class="text-center py-16 sm:py-24 lg:py-32">
                    <h1 class="text-4xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-6xl">Go Fast CMS</h1>
                    <p class="mt-6 text-lg leading-8 text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">`)
		sb.WriteString(data.Description()) // Use WriteString for Go variables/functions
		sb.WriteString(`</p>
                    <div class="mt-10 flex items-center justify-center gap-x-6">
                        <a href="/content" class="rounded-md bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 dark:bg-indigo-500 dark:hover:bg-indigo-400">View Content</a>
                        <a href="/content/new" class="text-sm font-semibold leading-6 text-gray-900 dark:text-gray-100 hover:text-gray-700 dark:hover:text-gray-300">Create New <span aria-hidden="true">→</span></a>
                    </div>
                </div>`)
		return sb.String()
	}

//line internal/templates/pages/index.qtpl:27
	qw422016.N().S(`
    
    `)
//line internal/templates/pages/index.qtpl:29
	qw422016.N().S(layouts.BaseLayout(data, pageContent))
//line internal/templates/pages/index.qtpl:29
	qw422016.N().S(`
`)
//line internal/templates/pages/index.qtpl:30
}

//line internal/templates/pages/index.qtpl:30
func WriteIndexPage(qq422016 qtio422016.Writer, data *IndexData) {
//line internal/templates/pages/index.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/pages/index.qtpl:30
	StreamIndexPage(qw422016, data)
//line internal/templates/pages/index.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/pages/index.qtpl:30
}

//line internal/templates/pages/index.qtpl:30
func IndexPage(data *IndexData) string {
//line internal/templates/pages/index.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/pages/index.qtpl:30
	WriteIndexPage(qb422016, data)
//line internal/templates/pages/index.qtpl:30
	qs422016 := string(qb422016.B)
//line internal/templates/pages/index.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/pages/index.qtpl:30
	return qs422016
//line internal/templates/pages/index.qtpl:30
}
