// Code generated by qtc from "notfound.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../templates/pages/notfound.qtpl:1
package pages

//line ../templates/pages/notfound.qtpl:1
import "cms/internal/models"

//line ../templates/pages/notfound.qtpl:2
import "cms/internal/templates/layouts"

//line ../templates/pages/notfound.qtpl:3
import "strings"

//line ../templates/pages/notfound.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../templates/pages/notfound.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../templates/pages/notfound.qtpl:6
type NotFoundData = models.BasePageData

//line ../templates/pages/notfound.qtpl:9
func StreamNotFoundPage(qw422016 *qt422016.Writer, data *NotFoundData) {
//line ../templates/pages/notfound.qtpl:9
	qw422016.N().S(`
    `)
//line ../templates/pages/notfound.qtpl:11
	pageContent := func() string {
		var sb strings.Builder
		sb.WriteString(`<div class="text-center py-16 sm:py-24">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#7c86ff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-ship-icon lucide-ship"><path d="M12 10.189V14"/><path d="M12 2v3"/><path d="M19 13V7a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2v6"/><path d="M19.38 20A11.6 11.6 0 0 0 21 14l-8.188-3.639a2 2 0 0 0-1.624 0L3 14a11.6 11.6 0 0 0 2.81 7.76"/><path d="M2 21c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1s1.2 1 2.5 1c2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"/></svg>
                    <h1 class="text-4xl font-bold text-gray-700 dark:text-gray-200 mb-4">404 - Page Not Found</h1>
                    <p class="text-lg text-gray-500 dark:text-gray-400 mb-8">Oops! Looks like this page doesn't exist.</p>
                    <a href="/" class="px-5 py-2.5 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 dark:bg-indigo-500 dark:hover:bg-indigo-400">Go Home</a>
                </div>`)
		return sb.String()
	}

//line ../templates/pages/notfound.qtpl:21
	qw422016.N().S(`
    `)
//line ../templates/pages/notfound.qtpl:22
	qw422016.N().S(layouts.BaseLayout(data, pageContent))
//line ../templates/pages/notfound.qtpl:22
	qw422016.N().S(`
`)
//line ../templates/pages/notfound.qtpl:23
}

//line ../templates/pages/notfound.qtpl:23
func WriteNotFoundPage(qq422016 qtio422016.Writer, data *NotFoundData) {
//line ../templates/pages/notfound.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../templates/pages/notfound.qtpl:23
	StreamNotFoundPage(qw422016, data)
//line ../templates/pages/notfound.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line ../templates/pages/notfound.qtpl:23
}

//line ../templates/pages/notfound.qtpl:23
func NotFoundPage(data *NotFoundData) string {
//line ../templates/pages/notfound.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line ../templates/pages/notfound.qtpl:23
	WriteNotFoundPage(qb422016, data)
//line ../templates/pages/notfound.qtpl:23
	qs422016 := string(qb422016.B)
//line ../templates/pages/notfound.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line ../templates/pages/notfound.qtpl:23
	return qs422016
//line ../templates/pages/notfound.qtpl:23
}
