// Code generated by qtc from "notfound.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/pages/notfound.qtpl:1
package pages

//line internal/templates/pages/notfound.qtpl:1
import "cms/internal/models"

//line internal/templates/pages/notfound.qtpl:2
import "cms/internal/templates/layouts"

//line internal/templates/pages/notfound.qtpl:3
import "strings"

//line internal/templates/pages/notfound.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/pages/notfound.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/pages/notfound.qtpl:6
type NotFoundData = models.BasePageData

// {# NotFoundPage renders the 404 page. #}

//line internal/templates/pages/notfound.qtpl:10
func StreamNotFoundPage(qw422016 *qt422016.Writer, data *NotFoundData) {
//line internal/templates/pages/notfound.qtpl:10
	qw422016.N().S(`
    `)
//line internal/templates/pages/notfound.qtpl:12
	pageContent := func() string {
		var sb strings.Builder
		sb.WriteString(`<div class="text-center py-16">`)
		sb.WriteString(`<svg xmlns="http://www.w3.org/2000/svg" class="w-24 h-24 text-indigo-300 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1"><path stroke-linecap="round" stroke-linejoin="round" d="M12 11c.833-.833 2-1.167 3.5-1 1.5.167 2.5.833 3 2 .5 1.167.167 2.833-1 4.5C16.333 18.167 14.667 19 12 19c-2.667 0-4.333-.833-5.5-2.5-1.167-1.667-1.5-3.333-1-4.5.5-1.167 1.5-1.833 3-2 1.5-.167 2.667.167 3.5 1Zm-5 4h10M8 15a1 1 0 100-2 1 1 0 000 2Zm8 0a1 1 0 100-2 1 1 0 000 2Z" /></svg>`)
		sb.WriteString(`<h1 class="text-4xl font-bold text-gray-700 mb-4">404 - Not Found</h1>`)
		sb.WriteString(`<p class="text-lg text-gray-500 mb-8">Ups, page not found</p>`)
		sb.WriteString(`<a href="/" class="px-4 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700">to Home</a>`)
		sb.WriteString(`</div>`)
		return sb.String()
	}

//line internal/templates/pages/notfound.qtpl:22
	qw422016.N().S(`
    `)
//line internal/templates/pages/notfound.qtpl:23
	qw422016.N().S(layouts.BaseLayout(data, pageContent))
//line internal/templates/pages/notfound.qtpl:23
	qw422016.N().S(`
`)
//line internal/templates/pages/notfound.qtpl:24
}

//line internal/templates/pages/notfound.qtpl:24
func WriteNotFoundPage(qq422016 qtio422016.Writer, data *NotFoundData) {
//line internal/templates/pages/notfound.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/pages/notfound.qtpl:24
	StreamNotFoundPage(qw422016, data)
//line internal/templates/pages/notfound.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/pages/notfound.qtpl:24
}

//line internal/templates/pages/notfound.qtpl:24
func NotFoundPage(data *NotFoundData) string {
//line internal/templates/pages/notfound.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/pages/notfound.qtpl:24
	WriteNotFoundPage(qb422016, data)
//line internal/templates/pages/notfound.qtpl:24
	qs422016 := string(qb422016.B)
//line internal/templates/pages/notfound.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/pages/notfound.qtpl:24
	return qs422016
//line internal/templates/pages/notfound.qtpl:24
}
