// Code generated by qtc from "settings.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../templates/pages/settings.qtpl:1
package pages

//line ../templates/pages/settings.qtpl:1
import "cms/internal/models"

//line ../templates/pages/settings.qtpl:2
import "cms/internal/templates/layouts"

//line ../templates/pages/settings.qtpl:3
import "strings"

//line ../templates/pages/settings.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../templates/pages/settings.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../templates/pages/settings.qtpl:6
type SettingsData = models.BasePageData

//line ../templates/pages/settings.qtpl:9
func StreamSettingsPage(qw422016 *qt422016.Writer, data *SettingsData) {
//line ../templates/pages/settings.qtpl:9
	qw422016.N().S(`
    `)
//line ../templates/pages/settings.qtpl:11
	pageContent := func() string {
		var sb strings.Builder
		sb.WriteString(`<div class="text-center py-16 sm:py-24">
                    <h1 class="text-4xl font-bold text-gray-700 dark:text-gray-200 mb-4">Settings</h1>
                    <p class="text-lg text-gray-500 dark:text-gray-400">This page is under construction.</p>
                </div>`)
		return sb.String()
	}

//line ../templates/pages/settings.qtpl:19
	qw422016.N().S(`
    `)
//line ../templates/pages/settings.qtpl:20
	qw422016.N().S(layouts.BaseLayout(data, pageContent))
//line ../templates/pages/settings.qtpl:20
	qw422016.N().S(`
`)
//line ../templates/pages/settings.qtpl:21
}

//line ../templates/pages/settings.qtpl:21
func WriteSettingsPage(qq422016 qtio422016.Writer, data *SettingsData) {
//line ../templates/pages/settings.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../templates/pages/settings.qtpl:21
	StreamSettingsPage(qw422016, data)
//line ../templates/pages/settings.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line ../templates/pages/settings.qtpl:21
}

//line ../templates/pages/settings.qtpl:21
func SettingsPage(data *SettingsData) string {
//line ../templates/pages/settings.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line ../templates/pages/settings.qtpl:21
	WriteSettingsPage(qb422016, data)
//line ../templates/pages/settings.qtpl:21
	qs422016 := string(qb422016.B)
//line ../templates/pages/settings.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line ../templates/pages/settings.qtpl:21
	return qs422016
//line ../templates/pages/settings.qtpl:21
}
