// Code generated by qtc from "view.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/pages/view.qtpl:1
package pages

//line internal/templates/pages/view.qtpl:1
import "cms/internal/models"

//line internal/templates/pages/view.qtpl:2
import "cms/internal/templates/layouts"

//line internal/templates/pages/view.qtpl:3
import "strings"

//line internal/templates/pages/view.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/pages/view.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/pages/view.qtpl:6
// ViewData struct is defined in models package
type ViewData = models.ViewData

// ViewPage renders a single content item view page.

//line internal/templates/pages/view.qtpl:11
func StreamViewPage(qw422016 *qt422016.Writer, data *ViewData) {
//line internal/templates/pages/view.qtpl:11
	qw422016.N().S(`
    `)
//line internal/templates/pages/view.qtpl:13
	pageContent := func() string {
		var sb strings.Builder
		sb.WriteString(`<article class="prose lg:prose-xl mx-auto bg-white p-6 rounded shadow">
                <h1>`)
		sb.WriteString(data.Item.Title)
		sb.WriteString(`</h1>
                <p class="text-sm text-gray-500">Status: `)
		sb.WriteString(data.Item.Status)
		sb.WriteString(`, Last Updated: `)
		sb.WriteString(data.Item.UpdatedAt.Format("January 2, 2006"))
		sb.WriteString(`</p>
                
                <div>
                    <!-- WARNING: Assuming data.Item.Content is safe HTML. Sanitize if necessary! -->
                    `)
		// Use WriteString to append the potentially unsafe HTML content
		sb.WriteString(data.Item.Content)
		sb.WriteString(`
                </div>
                
                <div class="mt-8 border-t pt-4">
                    <a href="/content/`)
		sb.WriteString(data.Item.ID)
		sb.WriteString(`/edit" class="text-indigo-600 hover:text-indigo-900 mr-4">Edit this item</a>
                    <a href="/content" class="text-gray-600 hover:text-gray-900">Back to list</a>
                </div>
            </article>`)
		return sb.String()
	}

//line internal/templates/pages/view.qtpl:42
	qw422016.N().S(`
    `)
//line internal/templates/pages/view.qtpl:43
	qw422016.N().S(layouts.BaseLayout(data, pageContent))
//line internal/templates/pages/view.qtpl:43
	qw422016.N().S(`
`)
//line internal/templates/pages/view.qtpl:44
}

//line internal/templates/pages/view.qtpl:44
func WriteViewPage(qq422016 qtio422016.Writer, data *ViewData) {
//line internal/templates/pages/view.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/pages/view.qtpl:44
	StreamViewPage(qw422016, data)
//line internal/templates/pages/view.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/pages/view.qtpl:44
}

//line internal/templates/pages/view.qtpl:44
func ViewPage(data *ViewData) string {
//line internal/templates/pages/view.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/pages/view.qtpl:44
	WriteViewPage(qb422016, data)
//line internal/templates/pages/view.qtpl:44
	qs422016 := string(qb422016.B)
//line internal/templates/pages/view.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/pages/view.qtpl:44
	return qs422016
//line internal/templates/pages/view.qtpl:44
}
