// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../templates/layouts/base.qtpl:1
package layouts

//line ../templates/layouts/base.qtpl:1
import "cms/internal/models"

//line ../templates/layouts/base.qtpl:2
import "cms/internal/templates/components"

//line ../templates/layouts/base.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../templates/layouts/base.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../templates/layouts/base.qtpl:5
// PageData is the interface required by the BaseLayout function.
type PageData = models.PageData

//line ../templates/layouts/base.qtpl:8
func StreamBaseLayout(qw422016 *qt422016.Writer, data PageData, pageContent func() string) {
//line ../templates/layouts/base.qtpl:8
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en" 
      x-data="{ theme: localStorage.getItem('theme') || 'light' }" 
      x-init="$watch('theme', val => localStorage.setItem('theme', val)); document.documentElement.setAttribute('data-theme', theme)" 
      :data-theme="theme">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>`)
//line ../templates/layouts/base.qtpl:17
	qw422016.E().S(data.Title())
//line ../templates/layouts/base.qtpl:17
	qw422016.N().S(`</title>
    <meta name="description" content="`)
//line ../templates/layouts/base.qtpl:18
	qw422016.E().S(data.Description())
//line ../templates/layouts/base.qtpl:18
	qw422016.N().S(`">
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NyA0MCIgZmlsbD0iIzBlYTVlOSI+DQogICAgPHBhdGggZD0iTTIzLjUgNi41QzE3LjUgNi41IDEzLjc1IDkuNSAxMi4yNSAxNS41QzE0LjUgMTIuNSAxNy4xMjUgMTEuMzc1IDIwLjEyNSAxMi4xMjVDMjEuODM2NyAxMi41NTI5IDIzLjA2MDEgMTMuNzk0NyAyNC40MTQyIDE1LjE2OTJDMjYuNjIwMiAxNy40MDg0IDI5LjE3MzQgMjAgMzQuNzUgMjBDNDAuNzUgMjAgNDQuNSAxNyA0NiAxMUM0My43NSAxNCA0MS4xMjUgMTUuMTI1IDM4LjEyNSAxNC4zNzVDMzYuNDEzMyAxMy45NDcxIDM1LjE4OTkgMTIuNzA1MyAzMy44MzU3IDExLjMzMDhDMzEuNjI5NyA5LjA5MTU4IDI5LjA3NjYgNi41IDIzLjUgNi41Wk0xMi4yNSAyMEM2LjI1IDIwIDIuNSAyMyAxIDI5QzMuMjUgMjYgNS44NzUgMjQuODc1IDguODc1IDI1LjYyNUMxMC41ODY3IDI2LjA1MjkgMTEuODEwMSAyNy4yOTQ3IDEzLjE2NDIgMjguNjY5M0MxNS4zNzAyIDMwLjkwODQgMTcuOTIzNCAzMy41IDIzLjUgMzMuNUMyOS41IDMzLjUgMzMuMjUgMzAuNSAzNC43NSAyNC41QzMyLjUgMjcuNSAyOS44NzUgMjguNjI1IDI2Ljg3NSAyNy44NzVDMjUuMTYzMyAyNy40NDcxIDIzLjkzOTkgMjYuMjA1MyAyMi41ODU4IDI0LjgzMDdDMjAuMzc5OCAyMi41OTE2IDE3LjgyNjYgMjAgMTIuMjUgMjBaIj48L3BhdGg+DQo8L3N2Zz4=" />
    
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <style>
        /* Basic style to prevent flash of unstyled content with Alpine.js */
        [x-cloak] { display: none !important; }
    </style>
    <style type="text/tailwindcss">
      @custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));
    </style>
</head>
<body class="bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 flex flex-col min-h-screen antialiased">
    <!-- Render the header component, passing the page data -->
    `)
//line ../templates/layouts/base.qtpl:32
	qw422016.N().S(components.Header(data))
//line ../templates/layouts/base.qtpl:32
	qw422016.N().S(`

    <main class="container mx-auto px-4 sm:px-6 lg:px-8 py-8 mt-16 flex-grow">
        <!-- Render the page-specific content passed as a function -->
        `)
//line ../templates/layouts/base.qtpl:36
	qw422016.N().S(pageContent())
//line ../templates/layouts/base.qtpl:36
	qw422016.N().S(`
    </main>

    <!-- Render the footer component -->
    `)
//line ../templates/layouts/base.qtpl:40
	qw422016.N().S(components.Footer())
//line ../templates/layouts/base.qtpl:40
	qw422016.N().S(`
</body>
</html>
`)
//line ../templates/layouts/base.qtpl:43
}

//line ../templates/layouts/base.qtpl:43
func WriteBaseLayout(qq422016 qtio422016.Writer, data PageData, pageContent func() string) {
//line ../templates/layouts/base.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../templates/layouts/base.qtpl:43
	StreamBaseLayout(qw422016, data, pageContent)
//line ../templates/layouts/base.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line ../templates/layouts/base.qtpl:43
}

//line ../templates/layouts/base.qtpl:43
func BaseLayout(data PageData, pageContent func() string) string {
//line ../templates/layouts/base.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line ../templates/layouts/base.qtpl:43
	WriteBaseLayout(qb422016, data, pageContent)
//line ../templates/layouts/base.qtpl:43
	qs422016 := string(qb422016.B)
//line ../templates/layouts/base.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line ../templates/layouts/base.qtpl:43
	return qs422016
//line ../templates/layouts/base.qtpl:43
}
