// Code generated by qtc from "plain.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// No models import needed here as PlainPageData is defined locally
//

//line internal/templates/layouts/plain.qtpl:3
package layouts

//line internal/templates/layouts/plain.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/layouts/plain.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/layouts/plain.qtpl:4
// PageData interface for plain layout (might only need BasePageData fields)
type PlainPageData interface {
	Title() string
	Description() string
	// No IsAuthenticated needed if header/footer are omitted
}

//line internal/templates/layouts/plain.qtpl:12
func StreamPlainLayout(qw422016 *qt422016.Writer, data PlainPageData, pageContent func() string) {
//line internal/templates/layouts/plain.qtpl:12
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en"
      x-data="{ theme: localStorage.getItem('theme') || 'light' }"
      x-init="$watch('theme', val => localStorage.setItem('theme', val));
              if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
              } else {
                  document.documentElement.classList.remove('dark');
              }"
      :class="{ 'dark': theme === 'dark' }" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>`)
//line internal/templates/layouts/plain.qtpl:26
	qw422016.E().S(data.Title())
//line internal/templates/layouts/plain.qtpl:26
	qw422016.N().S(`</title>
    <meta name="description" content="`)
//line internal/templates/layouts/plain.qtpl:27
	qw422016.E().S(data.Description())
//line internal/templates/layouts/plain.qtpl:27
	qw422016.N().S(`">
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NyA0MCIgZmlsbD0iIzBlYTVlOSI+DQogICAgPHBhdGggZD0iTTIzLjUgNi41QzE3LjUgNi41IDEzLjc1IDkuNSAxMi4yNSAxNS41QzE0LjUgMTIuNSAxNy4xMjUgMTEuMzc1IDIwLjEyNSAxMi4xMjVDMjEuODM2NyAxMi41NTI5IDIzLjA2MDEgMTMuNzk0NyAyNC40MTQyIDE1LjE2OTJDMjYuNjIwMiAxNy40MDg0IDI5LjE3MzQgMjAgMzQuNzUgMjBDNDAuNzUgMjAgNDQuNSAxNyA0NiAxMUM0My43NSAxNCA0MS4xMjUgMTUuMTI1IDM4LjEyNSAxNC4zNzVDMzYuNDEzMyAxMy45NDcxIDM1LjE4OTkgMTIuNzA1MyAzMy44MzU3IDExLjMzMDhDMzEuNjI5NyA5LjA5MTU4IDI5LjA3NjYgNi41IDIzLjUgNi41Wk0xMi4yNSAyMEM2LjI1IDIwIDIuNSAyMyAxIDI5QzMuMjUgMjYgNS44NzUgMjQuODc1IDguODc1IDI1LjYyNUMxMC41ODY3IDI2LjA1MjkgMTEuODEwMSAyNy4yOTQ3IDEzLjE2NDIgMjguNjY5M0MxNS4zNzAyIDMwLjkwODQgMTcuOTIzNCAzMy41IDIzLjUgMzMuNUMyOS41IDMzLjUgMzMuMjUgMzAuNSAzNC43NSAyNC41QzMyLjUgMjcuNSAyOS44NzUgMjguNjI1IDI2Ljg3NSAyNy44NzVDMjUuMTYzMyAyNy40NDcxIDIzLjkzOTkgMjYuMjA1MyAyMi41ODU4IDI0LjgzMDdDMjAuMzc5OCAyMi41OTE2IDE3LjgyNjYgMjAgMTIuMjUgMjBaIj48L3BhdGg+DQo8L3N2Zz4=" />

    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <style>
        /* Basic style to prevent flash of unstyled content with Alpine.js */
        [x-cloak] { display: none !important; }
    </style>
    <style type="text/tailwindcss">
      /* Define dark mode based on the .dark class on html */
      @custom-variant dark (&:where(.dark, .dark *));
    </style>
</head>
<body class="bg-gray-100 dark:bg-gray-900 flex items-center justify-center min-h-screen antialiased">
    <!-- Render only the page-specific content -->
    `)
//line internal/templates/layouts/plain.qtpl:42
	qw422016.N().S(pageContent())
//line internal/templates/layouts/plain.qtpl:42
	qw422016.N().S(`
</body>
</html>
`)
//line internal/templates/layouts/plain.qtpl:45
}

//line internal/templates/layouts/plain.qtpl:45
func WritePlainLayout(qq422016 qtio422016.Writer, data PlainPageData, pageContent func() string) {
//line internal/templates/layouts/plain.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/layouts/plain.qtpl:45
	StreamPlainLayout(qw422016, data, pageContent)
//line internal/templates/layouts/plain.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/layouts/plain.qtpl:45
}

//line internal/templates/layouts/plain.qtpl:45
func PlainLayout(data PlainPageData, pageContent func() string) string {
//line internal/templates/layouts/plain.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/layouts/plain.qtpl:45
	WritePlainLayout(qb422016, data, pageContent)
//line internal/templates/layouts/plain.qtpl:45
	qs422016 := string(qb422016.B)
//line internal/templates/layouts/plain.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/layouts/plain.qtpl:45
	return qs422016
//line internal/templates/layouts/plain.qtpl:45
}
