// Code generated by qtc from "footer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../templates/components/footer.qtpl:1
package components

//line ../templates/components/footer.qtpl:1
import "time"

//line ../templates/components/footer.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../templates/components/footer.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../templates/components/footer.qtpl:3
func StreamFooter(qw422016 *qt422016.Writer) {
//line ../templates/components/footer.qtpl:3
	qw422016.N().S(`
<footer class="bg-white dark:bg-gray-800 mt-auto border-t border-gray-200 dark:border-gray-700">
    <div class="container mx-auto px-6 py-8 md:flex md:items-center md:justify-between lg:px-8">
        <div class="flex justify-center space-x-6 md:order-2">
            <a href="#" class="text-gray-400 hover:text-gray-500 dark:hover:text-gray-300">
                <span class="sr-only">Facebook</span>
                 <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                    <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12Z" clip-rule="evenodd" />
                </svg>
            </a>
        </div>
        <div class="mt-8 md:order-1 md:mt-0">
            <p class="text-center text-sm leading-5 text-gray-500 dark:text-gray-400">&copy; `)
//line ../templates/components/footer.qtpl:15
	qw422016.N().D(time.Now().Year())
//line ../templates/components/footer.qtpl:15
	qw422016.N().S(` Go Fast CMS. All rights reserved.</p>
        </div>
    </div>
</footer>
`)
//line ../templates/components/footer.qtpl:19
}

//line ../templates/components/footer.qtpl:19
func WriteFooter(qq422016 qtio422016.Writer) {
//line ../templates/components/footer.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../templates/components/footer.qtpl:19
	StreamFooter(qw422016)
//line ../templates/components/footer.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line ../templates/components/footer.qtpl:19
}

//line ../templates/components/footer.qtpl:19
func Footer() string {
//line ../templates/components/footer.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line ../templates/components/footer.qtpl:19
	WriteFooter(qb422016)
//line ../templates/components/footer.qtpl:19
	qs422016 := string(qb422016.B)
//line ../templates/components/footer.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line ../templates/components/footer.qtpl:19
	return qs422016
//line ../templates/components/footer.qtpl:19
}
