// Code generated by qtc from "footer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/templates/components/footer.qtpl:1
package components

//line internal/templates/components/footer.qtpl:1
import "time"

//line internal/templates/components/footer.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/templates/components/footer.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/templates/components/footer.qtpl:3
func StreamFooter(qw422016 *qt422016.Writer) {
//line internal/templates/components/footer.qtpl:3
	qw422016.N().S(`
<footer class="bg-white mt-auto">
    <div class="mx-auto max-w-7xl px-6 py-12 md:flex md:items-center md:justify-between lg:px-8">
        <div class="mt-8 md:order-1 md:mt-0">
            <p class="text-center text-xs leading-5 text-gray-500">&copy; `)
//line internal/templates/components/footer.qtpl:7
	qw422016.N().D(time.Now().Year())
//line internal/templates/components/footer.qtpl:7
	qw422016.N().S(` CMS. All rights reserved.</p>
        </div>
    </div>
</footer>
`)
//line internal/templates/components/footer.qtpl:11
}

//line internal/templates/components/footer.qtpl:11
func WriteFooter(qq422016 qtio422016.Writer) {
//line internal/templates/components/footer.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/templates/components/footer.qtpl:11
	StreamFooter(qw422016)
//line internal/templates/components/footer.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line internal/templates/components/footer.qtpl:11
}

//line internal/templates/components/footer.qtpl:11
func Footer() string {
//line internal/templates/components/footer.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/templates/components/footer.qtpl:11
	WriteFooter(qb422016)
//line internal/templates/components/footer.qtpl:11
	qs422016 := string(qb422016.B)
//line internal/templates/components/footer.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/templates/components/footer.qtpl:11
	return qs422016
//line internal/templates/components/footer.qtpl:11
}
